{{- if .Values.ingress.enabled }}

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.healthcheck.path }}

  labels:
    app: {{ .Values.appName }}
spec:
  rules:
  - host: {{ .Values.appName }}-apps.demo.ort.edu.uy
    http:
      paths:
        - path: /*
          backend:
            serviceName: {{ .Values.appName }}
            servicePort: {{ .Values.service.port }}

{{- end }}